# コード非同期チェック
[[plugins]]
repo = 'dense-analysis/ale'
hook_source = '''
let g:ale_sign_column_always = 1
let g:ale_sign_error = '!!'
let g:ale_sign_warning = '=='
'''

# --------------------------------------
# Deoplete コード補完
# --------------------------------------

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
if has('conceal')
  set conceallevel=0 concealcursor=niv
endif
'''
on_event = 'InsertEnter'
depends = ['neosnippet-snippets']

[[plugins]]
repo= 'Shougo/neosnippet-snippets'

# --------------------------------------
# Emmet
# --------------------------------------
[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1
hook_add = '''
let g:user_emmet_leader_key='<C-e>'
let g:user_emmet_settings = {
\   'variables': {
\       'lang': "ja"
\   },
\   'html': {
\       'comment_type': 'lastonly'
\   }
\ }
'''

# --------------------------------------
# カーソル位置のコンテキストのfiletypeを判定しシンタックスを切り替える
# --------------------------------------
[[plugins]]  
repo = 'Shougo/context_filetype.vim'

[[plugins]] 
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
hook_add = '''
source ~/.config/nvim/plugins/vim-precious.rc.vim
'''

# -----------------------------------------
# シンタックス
# -----------------------------------------

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft= ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft= ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'alampros/vim-styled-jsx'
on_ft= ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'elzr/vim-json'
on_ft= ['json']
hook_add = '''
" ダブルクオテーション省略機能無効化
let g:vim_json_syntax_conceal = 0
'''

# [[plugins]]
# repo = 'leafgarland/typescript-vim'
# on_ft= ['typescript', 'typescript.tsx']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft= ['typescript', 'typescript.tsx']

[[plugins]] # TOMLシンタックス
repo = 'cespare/vim-toml'
on_ft= ['toml']

[[plugins]] # HTML5
repo = 'othree/html5.vim'

[[plugins]] # CSS3
repo = 'hail2u/vim-css3-syntax'

[[plugins]] # ES6
repo = 'othree/yajs.vim'

[[plugins]] # ejs
repo = 'nikvdp/ejs-syntax'

[[plugins]] # Smarty
repo = 'vim-scripts/smarty-syntax'

[[plugins]] # twig
repo = 'beyondwords/vim-twig'
on_ft= ['twig', 'html.twig']

[[plugins]] # pug
repo = 'digitaltoad/vim-pug'
on_ft= ['pug']

[[plugins]] # vue
repo = 'posva/vim-vue'

