# ----------------------------------------------------
# Dein プラグインマネジャー
# ----------------------------------------------------

[[plugins]]
repo = 'Shougo/dein.vim'

# ----------------------------------------------------
# Denite
# ----------------------------------------------------

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

# ----------------------------------------------------
# Defx ファイラー
# ----------------------------------------------------

[[plugins]]
repo ="kristijanhusak/defx-git"
hook_add = '''
call defx#custom#column('git', 'indicators', {
  \ 'Modified'  : '✹',
  \ 'Staged'    : '✚',
  \ 'Untracked' : '✭',
  \ 'Renamed'   : '➜',
  \ 'Unmerged'  : '═',
  \ 'Ignored'   : '☒',
  \ 'Deleted'   : '✖',
  \ 'Unknown'   : '?'
  \ })
'''

[[plugins]]
repo ="kristijanhusak/defx-icons"

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = '''
source ~/.config/nvim/plugins/defx.rc.vim
'''

# ----------------------------------------------------
# Deol ※NeoVim上でターミナルを実行できる
# ----------------------------------------------------

# XXX 動きがもっさりするので使用しない
# [[plugins]]
# repo = "shougo/deol.nvim"
# hook_add = """
# source ~/.config/nvim/plugins/deol.rc.vim
# """

# -----------------------------------------------------

[[plugins]] # コメント
# repo = 'tpope/vim-commentary'
repo = 'tomtom/tcomment_vim'

[[plugins]] # インデントに色を付けて見やすくする
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
'''

[[plugins]] # シングル・ダブルクウォートの入れ替えなど
repo = 'tpope/vim-surround'
hook_add = '''
" ビジュアルモードで選択後、"S-"入力で選択範囲をpタグで囲む
let g:surround_{char2nr("-")} = "<p>\r</p>"
'''

[[plugins]] # Agコマンドで検索を高速にする
repo = 'rking/ag.vim'

[[plugins]] # テキスト揃えを簡単に実現する
repo = 'junegunn/vim-easy-align'

[[plugins]] # 任意の２か所のdiffをマークする
repo = 'AndrewRadev/linediff.vim'

[[plugins]] 
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.rc.vim
'''

# -----------------------------------------
# Git関連
# -----------------------------------------

[[plugins]] # vim用gitラッパープラグイン
repo ='tpope/vim-fugitive'

# [[plugins]] # git の変更箇所を左側にマーク
repo = 'airblade/vim-gitgutter'

# -----------------------------------------
# カラースキーム
# -----------------------------------------

[[plugins]]
repo = 'haishanh/night-owl.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'whatyouhide/vim-gotham'

[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

# ----------------------------------------------------
# Markdown関連
# ----------------------------------------------------

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
autocmd BufRead,BufNewFile *.md  set filetype=markdown
nnoremap <silent> <Leader>po :PrevimOpen<CR>
let g:vim_markdown_folding_disabled=1
let g:previm_enable_realtime=1
'''
[[plugins]]
repo = 'tyru/open-browser.vim'

# -----------------------------------------------------
# GO
# -----------------------------------------------------

[[plugins]]
repo = 'fatih/vim-go'

# -----------------------------------------------------
# %による移動の強化
# -----------------------------------------------------

[[plugins]]
repo = 'andymass/vim-matchup'

